name: plant_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  dio: ^5.9.0
  get_it: ^9.0.5
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.2
  persistent_bottom_nav_bar_v2: ^6.2.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.6.2
  very_good_analysis: ^5.1.0

flutter_gen:
  integrations:
    flutter_svg: true  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
